version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing backend dependencies"

  pre_build:
    commands:
      - echo "No separate dependencies needed for Lambda"

  build:
    commands:
      # -------------------------------
      # 打包 image-indexing-lambda
      # -------------------------------
      - echo "Packaging image-indexing-lambda"
      - cd backend/image-indexing-lambda
      - rm -f function.zip       # 防呆（忘記刪 repo 也能保護）
      - zip -r ../../image-indexing-lambda.zip .
      - cd ../../

      # -------------------------------
      # 打包 search-lambda
      # -------------------------------
      - echo "Packaging search-lambda"
      - cd backend/search-lambda
      - zip -r ../../search-lambda.zip .
      - cd ../../

      # -------------------------------
      # 更新 Lambda
      # -------------------------------
      - echo "Updating image-indexing-lambda..."
      - aws lambda update-function-code \
          --function-name image-indexing-lambda \
          --zip-file fileb://image-indexing-lambda.zip

      - echo "Updating search-lambda..."
      - aws lambda update-function-code \
          --function-name search-lambda \
          --zip-file fileb://search-lambda.zip

artifacts:
  files:
    - image-indexing-lambda.zip
    - search-lambda.zip
